### ISSUE TITLE
Warnings appearing while scanning multiple tenants in same session

### ISSUE THREAD

**Issue by saikumarra** [azsk/EntraIDScanner#27]
Getting lot of warnings when doing the scan while switching the tenant in same session

Repro steps: 
1) Run the scan with personal tenant
2) Rerun the scan with another tenant in same session. 
3) Observe that the below logs are appearing in console.
![image](https://github.com/azsk/EntraIDScanner/assets/135116153/ec0872f7-92ba-4cf9-8fbd-56247c648d69)

**Comment by arunchandrapant** [comment]
I am seeing same issue.
